[tool.check-unicode]
exclude-patterns = [ "fish/**/*", "waybar/.config/waybar/config.jsonc" ]
allow-codepoints = [
  "U+2192", # RIGHTWARDS ARROW [Sm]
  "U+25CF", # BLACK CIRCLE [So]
  "U+00B7", # U+00B7 MIDDLE DOT [Po]
  "U+E0B0", # vim/.config/nvim/init.vim U+E0B0 [Co]
  "U+E0B1", # vim/.config/nvim/init.vim U+E0B1 [Co]
  "U+E0B2", # vim/.config/nvim/init.vim U+E0B2 [Co]
  "U+E0B3", # vim/.config/nvim/init.vim U+E0B3 [Co]
  "U+E0A0", # vim/.config/nvim/init.vim U+E0A0 [Co]
  "U+E0A2", # vim/.config/nvim/init.vim U+E0A2 [Co]
  "U+2630", # vim/.config/nvim/init.vim TRIGRAM FOR HEAVEN [So]
  "U+E0A1", # vim/.config/nvim/init.vim U+E0A1 [Co]
  "U+26A1", # vim/.config/nvim/init.vim HIGH VOLTAGE SIGN [So]
  "U+00B0", # waybar/.config/waybar/temps.sh U+00B0 DEGREE SIGN [So]
]
